name: flysystem-bundle

on:
    pull_request: ~
    push:
        branches:
            - 1.x
            - 2.x
            - 3.x

jobs:
    coding-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  coverage: none
            - name: php-cs-fixer
              run: |
                  wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v3.13.2/php-cs-fixer.phar -q
                  php php-cs-fixer.phar fix --dry-run --diff

    tests-php-8-0-symfony-5-4:
        runs-on: ubuntu-latest
        env:
            SYMFONY_VERSION: 5.4.*
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  coverage: none
            - name: PHPUnit
              run: |
                  composer require --no-update symfony/config=$SYMFONY_VERSION symfony/http-kernel=$SYMFONY_VERSION symfony/dependency-injection=$SYMFONY_VERSION symfony/options-resolver=$SYMFONY_VERSION
                  composer require --no-update --dev symfony/framework-bundle=$SYMFONY_VERSION symfony/yaml=$SYMFONY_VERSION
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit

    tests-php-8-0-symfony-6-0:
        runs-on: ubuntu-latest
        env:
            SYMFONY_VERSION: 6.0.*
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  coverage: none
            - name: PHPUnit
              run: |
                  composer require --no-update symfony/config=$SYMFONY_VERSION symfony/http-kernel=$SYMFONY_VERSION symfony/dependency-injection=$SYMFONY_VERSION symfony/options-resolver=$SYMFONY_VERSION
                  composer require --no-update --dev symfony/framework-bundle=$SYMFONY_VERSION symfony/yaml=$SYMFONY_VERSION
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit

    tests-php-8-1-symfony-6-1:
        runs-on: ubuntu-latest
        env:
            SYMFONY_VERSION: 6.1.*
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  coverage: none
            - name: PHPUnit
              run: |
                  composer require --no-update symfony/config=$SYMFONY_VERSION symfony/http-kernel=$SYMFONY_VERSION symfony/dependency-injection=$SYMFONY_VERSION symfony/options-resolver=$SYMFONY_VERSION
                  composer require --no-update --dev symfony/framework-bundle=$SYMFONY_VERSION symfony/yaml=$SYMFONY_VERSION
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit

    tests-php-8-1-symfony-6-2:
        runs-on: ubuntu-latest
        env:
            SYMFONY_VERSION: 6.2.*
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  coverage: none
            - name: PHPUnit
              run: |
                  composer require --no-update symfony/config=$SYMFONY_VERSION symfony/http-kernel=$SYMFONY_VERSION symfony/dependency-injection=$SYMFONY_VERSION symfony/options-resolver=$SYMFONY_VERSION
                  composer require --no-update --dev symfony/framework-bundle=$SYMFONY_VERSION symfony/yaml=$SYMFONY_VERSION
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit

    tests-php-8-2-symfony-6-1:
        runs-on: ubuntu-latest
        env:
            SYMFONY_VERSION: 6.1.*
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  coverage: none
            - name: PHPUnit
              run: |
                  composer require --no-update symfony/config=$SYMFONY_VERSION symfony/http-kernel=$SYMFONY_VERSION symfony/dependency-injection=$SYMFONY_VERSION symfony/options-resolver=$SYMFONY_VERSION
                  composer require --no-update --dev symfony/framework-bundle=$SYMFONY_VERSION symfony/yaml=$SYMFONY_VERSION
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit

    tests-php-8-2-symfony-6-2:
        runs-on: ubuntu-latest
        env:
            SYMFONY_VERSION: 6.2.*
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  coverage: none
            - name: PHPUnit
              run: |
                  composer require --no-update symfony/config=$SYMFONY_VERSION symfony/http-kernel=$SYMFONY_VERSION symfony/dependency-injection=$SYMFONY_VERSION symfony/options-resolver=$SYMFONY_VERSION
                  composer require --no-update --dev symfony/framework-bundle=$SYMFONY_VERSION symfony/yaml=$SYMFONY_VERSION
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit

    tests-php-8-2-symfony-6-3:
        runs-on: ubuntu-latest
        env:
            SYMFONY_VERSION: 6.3.*
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  coverage: none
            - name: PHPUnit
              run: |
                  composer require --no-update symfony/config=$SYMFONY_VERSION symfony/http-kernel=$SYMFONY_VERSION symfony/dependency-injection=$SYMFONY_VERSION symfony/options-resolver=$SYMFONY_VERSION
                  composer require --no-update --dev symfony/framework-bundle=$SYMFONY_VERSION symfony/yaml=$SYMFONY_VERSION
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
